server:
  port: 8080
  servlet:
    context-path: /mybatis

spring:
  application:
    name: mybatis_test_8080 #服务名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver #数据库驱动包
    url: jdbc:mysql://localhost:3307/cloud?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #  返回json的全局格式化时间
    time-zone: GMT+8 #不加此项，时间会少8个小时
  profiles:
    active: dev #dev-开发环境:application-dev.yml；test-测试环境:application-test.yml；prod-生产环境:application-prod.yml

#引入log4j2日志配置文件
logging:
  config: classpath:log4j2.xml

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
#  type-aliases-package: com.rj.springcloud.bean
  global-config:
    db-config:
      #逻辑删除配置（下面2个配置）
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)